/*
copyright xu(xusiwei1236@163.com), all right reserved.

Find the Difference
====================

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        int sc[128] = {0}, tc[128] = {0};
		for (int i = 0; i < s.length(); i++) sc[s[i]]++;
		for (int i = 0; i < t.length(); i++) tc[t[i]]++;
		for (int i = 0; i < sizeof(sc)/sizeof(sc[0]); i++) {
			if (sc[i] != tc[i]) return i;
		}
		return 0;
    }
};
