/*
copyright xu(xusiwei1236@163.com), all right reserved.

Find the Difference
====================

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

import java.util.Arrays;

public class Solution {
    public char findTheDifference(String s, String t) {
        char[] ss = s.toCharArray(); Arrays.sort(ss);
        char[] tt = t.toCharArray(); Arrays.sort(tt);
        for (int i = 0; i < ss.length; i++) {
            if (ss[i] != tt[i]) return tt[i];
        }
        return tt[tt.length - 1];
    }
    
    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        if (args.length >= 1) s = args[0];
        if (args.length >= 2) t = args[1];
        System.out.println(new Solution().findTheDifference(s, t));
    }
}

