/*
copyright xu(xusiwei1236@163.com), all right reserved.

Find the Difference
====================

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

public class Solution2 {
    public char findTheDifference(String s, String t) {
        int[] sc = new int[128];
        int[] tc = new int[128];
        for (char c: s.toCharArray()) sc[c]++;
        for (char c: t.toCharArray()) tc[c]++;
        for (int i = 0; i < sc.length; i++) {
            if (sc[i] != tc[i]) {
                return (char)i;
            }
        }
        return 0;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        if (args.length >= 1) s = args[0];
        if (args.length >= 2) t = args[1];
        System.out.println(new Solution2().findTheDifference(s, t));
    }
}

